name: psdigital_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">3.6.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Dependency Injection
  get_it: ^8.2.0
  
  # Network
  dio: ^5.9.0
  
  # Routing
  go_router: ^16.2.0
  
  # Functional Programming
  fpdart: ^1.1.1
  
  # State Management
  flutter_bloc: ^9.1.1
  
  # Environment Variables
  flutter_dotenv: ^6.0.0
  
  # Value Based Equality
  equatable: ^2.0.7
  
  # Pagination
  infinite_scroll_pagination: ^5.1.1
  
  # Loading Progress
  flutter_spinkit: ^5.2.2
  
  # Toasts
  toastification: ^3.0.3
  
  # UI Elements
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  bubble_box: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Bernier
      fonts:
        - asset: assets/fonts/bernier/BERNIER-Regular.ttf
    - family: Tablet Gothic Narrow
      fonts:
        - asset: assets/fonts/tablet_gothic_narrow/Tablet-Gothic-Narrow-Thin.ttf
          weight: 200
        - asset: assets/fonts/tablet_gothic_narrow/Tablet-Gothic-Narrow-Light.ttf
          weight: 300
        - asset: assets/fonts/tablet_gothic_narrow/Tablet-Gothic-Narrow-Rg.ttf
          weight: 400
        - asset: assets/fonts/tablet_gothic_narrow/Tablet-Gothic-Narrow-SmBd.ttf
          weight: 600
        - asset: assets/fonts/tablet_gothic_narrow/Tablet-Gothic-Narrow-Bold.ttf
          weight: 700
  
